### ISSUE TITLE
failure during rmd-app deployment script, list index out of range

### ISSUE THREAD

**Issue by javiisanchez** [PredixDev/predix-rmd-ref-app#17]
I'm doing the tutorial about Install the RMD Reference App, and when I'm runnig the script, I see the flollowing error:

Punto final de la API: https://api.system.aws-usw02-pr.ice.predix.io (Versi├│n de la API: 2.62.0) Usuario: j.sanchez.buitrago@accenture.com Organizaci├│n: j.sanchez.buitrago@accenture.com Espacio: PredixCloud

Traceback (most recent call last): File "installRefApp.py", line 5, in import refAppConfig as config File "C:\Users\j.sanchez.buitrago\predix-rmd-ref-app\scripts\refAppConfig.py", line 139, in user, org, space = checkRequirements() File "C:\Users\j.sanchez.buitrago\predix-rmd-ref-app\scripts\refAppConfig.py", line 10, in checkRequirements user = cfTarget.decode('utf8').split('User:')[1].split('Org:')[0] IndexError: list index out of range

Can you help me?

Thanks!

**Comment by turnerth** [comment]
please attach the whole log

**Comment by javiisanchez** [comment]
This is the complet register, I clone the github project:

git clone https://github.com/PredixDev/predix-rmd-ref-app.git
$ cd predix-rmd-ref-app

and finally:

python scripts/installRefApp.py

and the result of the run the script is the comented in the error.

**Comment by javiisanchez** [comment]
I don' understand that you want say with: please attach the whole log

**Comment by turnerth** [comment]
When you run the python script it prints out lots of statements.  Can you copy and paste them in to a txt file and attach it?

**Comment by javiisanchez** [comment]
Yes, the statement printed for Python script is the following:

Traceback (most recent call last): File "installRefApp.py", line 5, in import refAppConfig as config File "C:\Users\j.sanchez.buitrago\predix-rmd-ref-app\scripts\refAppConfig.py", line 139, in user, org, space = checkRequirements() File "C:\Users\j.sanchez.buitrago\predix-rmd-ref-app\scripts\refAppConfig.py", line 10, in checkRequirements user = cfTarget.decode('utf8').split('User:')[1].split('Org:')[0] IndexError: list index out of range

**Comment by turnerth** [comment]
let's work off the forum, i'm having trouble keeping all your posts straight.  I need more info.  please, on the forum, attach the entire output of the script.
