### ISSUE TITLE
Stuck at starting data-exchange while installing ReferenceApp

### ISSUE THREAD

**Issue by jerryatge** [PredixDev/predix-rmd-ref-app#30]
[data-exchange.log](https://github.com/PredixDev/predix-rmd-ref-app/files/1941681/data-exchange.log)
[quickstart.log](https://github.com/PredixDev/predix-rmd-ref-app/files/1941683/quickstart.log)

Hi Team,

I'm trying to install the Reference App following the instructions in the Predix Guide at [https://www.predix.io/resources/tutorials/tutorial-details.html?tutorial_id=2106&tag=1610&journey=Digital%20Twin%3A%20from%20the%20Edge%20to%20the%20Cloud%20using%20RMD%20Reference%20App&resources=1473,2106,1600](https://www.predix.io/resources/tutorials/tutorial-details.html?tutorial_id=2106&tag=1610&journey=Digital%20Twin%3A%20from%20the%20Edge%20to%20the%20Cloud%20using%20RMD%20Reference%20App&resources=1473,2106,1600
)
Right now I'm stuck at the process to deploy and start the app **data-exchange**, somehow the data-exchange could not be started, checking the logs of the app, I could see the following errors:

_2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT Error starting ApplicationContext. To display the auto-configuration report enabled debug logging (start with --debug)
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 08:07:12.157 [main] ERROR o.s.b.SpringApplication Groovy - Application startup failed
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webSocketHandler': Invocation of init method failed; nested exception is java.lang.RuntimeException: Encountered issue creating WebSocket in pool. 
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136) ~[spring-beans-4.1.6.RELEASE.jar!/:4.1.6.RELEASE]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408) ~[spring-beans-4.1.6.RELEASE.jar!/:4.1.6.RELEASE]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1566) ~[spring-beans-4.1.6.RELEASE.jar!/:4.1.6.RELEASE]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539) ~[spring-beans-4.1.6.RELEASE.jar!/:4.1.6.RELEASE]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476) ~[spring-beans-4.1.6.RELEASE.jar!/:4.1.6.RELEASE]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303) ~[spring-beans-4.1.6.RELEASE.jar!/:4.1.6.RELEASE]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.1.6.RELEASE.jar!/:4.1.6.RELEASE]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299) ~[spring-beans-4.1.6.RELEASE.jar!/:4.1.6.RELEASE]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194) ~[spring-beans-4.1.6.RELEASE.jar!/:4.1.6.RELEASE]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755) ~[spring-beans-4.1.6.RELEASE.jar!/:4.1.6.RELEASE]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757) ~[spring-context-4.1.6.RELEASE.jar!/:4.1.6.RELEASE]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480) ~[spring-context-4.1.6.RELEASE.jar!/:4.1.6.RELEASE]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.2.3.RELEASE.jar!/:1.2.3.RELEASE]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686) ~[spring-boot-1.2.3.RELEASE.jar!/:1.2.3.RELEASE]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320) ~[spring-boot-1.2.3.RELEASE.jar!/:1.2.3.RELEASE]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at com.ge.predix.solsvc.fdh.router.boot.FdhRouterApplication.main(FdhRouterApplication.java:61) [app/:na]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53) [app/:na]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT Caused by: java.lang.RuntimeException: Encountered issue creating WebSocket in pool. 
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at com.ge.predix.solsvc.websocket.client.WebSocketClientImpl.init(WebSocketClientImpl.java:91) ~[predix-websocket-client-2.1.60.jar!/:na]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at com.ge.predix.solsvc.fdh.handler.websocket.WebsocketHandler.init(WebsocketHandler.java:96) ~[fdh-websocket-handler-2.0.72.jar!/:na]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:349) ~[spring-beans-4.1.6.RELEASE.jar!/:4.1.6.RELEASE]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:300) ~[spring-beans-4.1.6.RELEASE.jar!/:4.1.6.RELEASE]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133) ~[spring-beans-4.1.6.RELEASE.jar!/:4.1.6.RELEASE]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	... 21 common frames omitted
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT Caused by: java.lang.RuntimeException: unable to make websocket connection to wss://Jerry.Ma-websocket-server.run.aws-usw02-pr.ice.predix.io/livestream/messages error=The status code of the opening handshake response is not '101 Switching Protocols'. The status line is: HTTP/1.1 404 Not Found config=DefaultOauthRestConfig [oauthIssuerId=https://acfc5fab-f65b-42bb-99a6-c22a1997ddb1.predix-uaa.run.aws-usw02-pr.ice.predix.io/oauth/token, oauthUri=https://acfc5fab-f65b-42bb-99a6-c22a1997ddb1.predix-uaa.run.aws-usw02-pr.ice.predix.io, proxyHost=null, proxyPort=null, oauthGrantType=client_credentials, oauthTokenType=JWT, oauthClientId=app_client_id:secret, oauthClientIdEncode=true, oauthUserName=null, oauthUserPassword=null, oauthEncodeUserPassword=false, oauthCertLocation=, oauthCertPassword=null, oauthConnectionTimeout=10000, oauthSocketTimeout=10000, poolMaxSize=10, poolValidateAfterInactivityTime=10000, poolConnectionRequestTimeout=10000, defaultConnectionTimeout=20000, defaultSocketTimeout=25000]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at com.ge.predix.solsvc.websocket.factory.WebSocketPoolableConnectionFactory.makeObject(WebSocketPoolableConnectionFactory.java:99) ~[predix-websocket-client-2.1.60.jar!/:na]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at org.apache.commons.pool.impl.GenericObjectPool.addObject(GenericObjectPool.java:1691) ~[commons-pool-1.6.jar!/:1.6]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at com.ge.predix.solsvc.websocket.client.WebSocketClientImpl.init(WebSocketClientImpl.java:86) ~[predix-websocket-client-2.1.60.jar!/:na]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	... 29 common frames omitted
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT Caused by: **com.neovisionaries.ws.client.WebSocketException: The status code of the opening handshake response is not '101 Switching Protocols'. The status line is: HTTP/1.1 404 Not Found**
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at com.neovisionaries.ws.client.WebSocket.readStatusLine(WebSocket.java:1677) ~[nv-websocket-client-1.3.jar!/:na]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at com.neovisionaries.ws.client.WebSocket.readHandshake(WebSocket.java:1612) ~[nv-websocket-client-1.3.jar!/:na]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at com.neovisionaries.ws.client.WebSocket.shakeHands(WebSocket.java:1511) ~[nv-websocket-client-1.3.jar!/:na]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at com.neovisionaries.ws.client.WebSocket.connect(WebSocket.java:822) ~[nv-websocket-client-1.3.jar!/:na]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	at com.ge.predix.solsvc.websocket.factory.WebSocketPoolableConnectionFactory.makeObject(WebSocketPoolableConnectionFactory.java:92) ~[predix-websocket-client-2.1.60.jar!/:na]
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]OUT 	... 31 common frames omitted
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]ERR java.lang.reflect.InvocationTargetException
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]ERR 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]ERR 	at java.lang.reflect.Method.invoke(Method.java:498)
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]ERR 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]ERR 	at java.lang.Thread.run(Thread.java:745)
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]ERR Caused by: **org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webSocketHandler': Invocation of init method failed; nested exception is java.lang.RuntimeException: Encountered issue creating WebSocket in pool.** 
2018-04-24T16:07:12.15+0800 [APP/PROC/WEB/0]ERR 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1566)
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	at com.ge.predix.solsvc.fdh.router.boot.FdhRouterApplication.main(FdhRouterApplication.java:61)
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	... 6 more
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR Caused by: java.lang.RuntimeException: Encountered issue creating WebSocket in pool. 
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	at com.ge.predix.solsvc.websocket.client.WebSocketClientImpl.init(WebSocketClientImpl.java:91)
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	at com.ge.predix.solsvc.fdh.handler.websocket.WebsocketHandler.init(WebsocketHandler.java:96)
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	at java.lang.reflect.Method.invoke(Method.java:498)
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:349)
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:300)
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	... 21 more
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR **Caused by: java.lang.RuntimeException: unable to make websocket connection to wss://Jerry.Ma-websocket-server.run.aws-usw02-pr.ice.predix.io/livestream/messages error=The status code of the opening handshake response is not '101 Switching Protocols'. The status line is: HTTP/1.1 404 Not Found config=DefaultOauthRestConfig [oauthIssuerId=https://acfc5fab-f65b-42bb-99a6-c22a1997ddb1.predix-uaa.run.aws-usw02-pr.ice.predix.io/oauth/token, oauthUri=https://acfc5fab-f65b-42bb-99a6-c22a1997ddb1.predix-uaa.run.aws-usw02-pr.ice.predix.io, proxyHost=null, proxyPort=null, oauthGrantType=client_credentials, oauthTokenType=JWT, oauthClientId=app_client_id:secret, oauthClientIdEncode=true, oauthUserName=null, oauthUserPassword=null, oauthEncodeUserPassword=false, oauthCertLocation=, oauthCertPassword=null, oauthConnectionTimeout=10000, oauthSocketTimeout=10000, poolMaxSize=10, poolValidateAfterInactivityTime=10000, poolConnectionRequestTimeout=10000, defaultConnectionTimeout=20000, defaultSocketTimeout=25000]**
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	at com.ge.predix.solsvc.websocket.factory.WebSocketPoolableConnectionFactory.makeObject(WebSocketPoolableConnectionFactory.java:99)
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	at org.apache.commons.pool.impl.GenericObjectPool.addObject(GenericObjectPool.java:1691)
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	at com.ge.predix.solsvc.websocket.client.WebSocketClientImpl.init(WebSocketClientImpl.java:86)
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	... 29 more
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR Caused by: com.neovisionaries.ws.client.WebSocketException: The status code of the opening handshake response is not '101 Switching Protocols'. The status line is: HTTP/1.1 404 Not Found
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	at com.neovisionaries.ws.client.WebSocket.readStatusLine(WebSocket.java:1677)
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	at com.neovisionaries.ws.client.WebSocket.readHandshake(WebSocket.java:1612)
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	at com.neovisionaries.ws.client.WebSocket.shakeHands(WebSocket.java:1511)
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	at com.neovisionaries.ws.client.WebSocket.connect(WebSocket.java:822)
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	at com.ge.predix.solsvc.websocket.factory.WebSocketPoolableConnectionFactory.makeObject(WebSocketPoolableConnectionFactory.java:92)
2018-04-24T16:07:12.16+0800 [APP/PROC/WEB/0]ERR 	... 31 more
2018-04-24T16:07:12.19+0800 [APP/PROC/WEB/0]OUT Exit status 1
2018-04-24T16:07:12.22+0800 [CELL/0]     OUT Destroying container
2018-04-24T16:07:12.24+0800 [API/6]      OUT Process has crashed with type: "web"
2018-04-24T16:07:12.27+0800 [API/6]      OUT App instance exited with guid 76aa7a8f-4758-43dd-a695-6b16cc9772e2 payload: {"instance"=>"", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"2 error(s) occurred:\n\n* 1 error(s) occurred:\n\n* Exited with status 1\n* cancelled", "crash_count"=>8, "crash_timestamp"=>1524557232214567838, "version"=>"e3e62274-1231-4d3b-9fcb-a2fa2f6a8113"}
2018-04-24T16:07:13.22+0800 [CELL/0]     OUT Successfully destroyed container_

Attached is the full log file of the app **Jerry.Ma-data-exchange** and  the **quickstart.log** which contains the procedure of the script quickstart-rmd-ref-app.bat. BTW, I'm running the Windows version with the  command line **@powershell -Command "(new-object net.webclient).DownloadFile('https://raw.githubusercontent.com/PredixDev/predix-rmd-ref-app/master/scripts/quickstart-rmd-ref-app.bat', 'quickstart-rmd-ref-app.bat')" && "quickstart-rmd-ref-app.bat"**

**Comment by susheelvc** [comment]
Hi Jerry,

Can you send us the log for Websocket Server?

cf logs Jerry.Ma-websocket-server --recent

**Comment by jerryatge** [comment]
Hi Susheel,

Thank you so much for looking at this issue. I checked the logs of the app Jerry.Ma-websocket-server, but it does not have any logs, see below cf logs result:

_**$ cf a
Getting apps in org jerry.ma@ge.com / space dev as jerry.ma@ge.com...
OK

name                        requested state   instances   memory   disk   urls
Jerry.Ma-data-exchange      started           0/1         512M     1G     jerryma-data-exchange.run.aws-usw02-pr.ice.predix.io
Jerry.Ma-websocket-server   started           1/1         512M     1G     jerryma-websocket-server.run.aws-usw02-pr.ice.predix.io

212573235@G9D4NFC2E ~
$ cf logs Jerry.Ma-websocket-server --recent
Connected, dumping recent logs for app Jerry.Ma-websocket-server in org jerry.ma@ge.com / space dev as jerry.ma@ge.com...**_

**Comment by jerryatge** [comment]
Hi Susheel,

I just restaged  the app Jerry.Ma-websocket-server, and now its logs appears, please find attached the log file. 
After restaging the websocket-server, I tried to restage the data-exchange, but still failed.

[websocket-server.log](https://github.com/PredixDev/predix-rmd-ref-app/files/1945174/websocket-server.log)
_

**Comment by turnerth** [comment]
Same error? can you attach the latest data-exchange log?

**Comment by jerryatge** [comment]
Hi Susheel,

It seems to be the same error. I'm attaching the latest error of the data-exchange log data-exchange-new.log. Thanks!
[data-exchange-new.log](https://github.com/PredixDev/predix-rmd-ref-app/files/1949960/data-exchange-new.log)

**Comment by turnerth** [comment]
Closing as I'm assuming this was resolved due to the age of this.  Let us know if not.
